---
title: '&nbsp;'
title-meta: "Stability-Report"
params:
  Stability: NA
  Options: NA
output:
  html_document:
    df_print: paged
  word_document:
    reference_docx: template.docx
---

### ***eCerto*** Report - Stability

```{r data, echo=FALSE}
# get a local representation of all data provided by Shiny
testing <- length(params$Stability)==1L && (is.na(params$Stability) | params$Stability=="NA")
if (testing) {
  res <- eCerto::CRM001
  S <- res[["Stability"]]
  O <- list(
    "apm" = NULL,
    "U_Def" = "2s",
    "mt" = res$General$materialtabelle,
    "type" = 1,
    "t_cert" = 60,
    "slope_of_means" = FALSE,
    "show_legend" = TRUE
  )
} else {
  S <- params$Stability
  O <- params$Options
}
an <- as.character(S[["s_vals"]][,"analyte"])
```

```{r Tab.S1, echo=FALSE, comment=NA, message=FALSE, warning=FALSE, results='asis'}
cat(paste0(
  "Date: ", format(Sys.time(), '%d %B, %Y'), "  \n"
  #"User: ", G$user, "  \n", 
  #"Material: ", G$study_id
), "\n\n")

eCerto:::styleTabS1(x = S[["s_vals"]], mt = data.frame("analyte"=an), output="ft")

# make individual plots to allow separate inclusion in i.e. Word reports
for (i in 1:length(an)) {
  try(
    eCerto:::plot_lts_data(
      x = eCerto:::prepFigS1(
        s = O[["s_Data"]],
        an = an[i],
        apm = O[["apm"]],
        U_Def = O[["U_Def"]],
        mt = O[["mt"]]
      ),
      type = O[["type"]],
      t_cert = O[["t_cert"]],
      slope_of_means = O[["slope_of_means"]],
      show_legend = O[["show_legend"]]
    )
  )
}

# show input data
eCerto:::ft_default(S[["data"]], caption = paste0("Imported analyte data from stability assay (file ", S[["input_files"]], ")"), id = "Tab.S0")
```
