default:
  golem_name: eCerto
  app_version: !expr as.character(utils::packageVersion("eCerto"))
  app_date: !expr as.character(Sys.Date())
  app_prod: no
  silent: no
production:
  app_prod: yes
  silent: yes
dev:
  golem_wd: !expr here::here()
  silent: no
