app <- ShinyDriver$new("../../")
app$snapshotInit("first analyte test (only loading, no validation test)")

app$setInputs(link_to_start = "click")
app$setInputs(`excelfile-moduleSelect` = "Certifications")
app$uploadFile(`excelfile-test-upld-xlsxfile-file` = c(
  system.file(package = "ecerto","extdata","Ergebnisblatt_BAM-M321_Aleris Koblenz_m.xlsx"), 
  system.file(package = "ecerto","extdata","Ergebnisblatt_BAM-M321_Aleris_Duffel_m.xlsx"), 
  system.file(package = "ecerto","extdata","Ergebnisblatt_BAM-M321_AMAG_Nasschemie_m.xlsx")
)) # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$setInputs(`excelfile-test-pam-rowslider` = c(5, 28))
app$setInputs(`excelfile-test-pam-rowslider` = c(7, 28))
app$setInputs(`excelfile-test-pam-rowslider` = c(7, 13))
app$setInputs(`excelfile-test-pam-rowslider` = c(7, 14))
app$setInputs(`excelfile-test-pam-colslider` = c(1, 14))
app$setInputs(`excelfile-test-pam-colslider` = c(1, 9))
app$setInputs(`excelfile-test-pam-colslider` = c(1, 8))
app$snapshot()
app$setInputs(`excelfile-go` = "click")
app$setInputs(`certification-cert_filter-flt_samplesSi` = character(0), wait_=FALSE, values_=FALSE)
app$setInputs(`certification-cert_filter-precisionSi` = 4, wait_=FALSE, values_=FALSE)
app$setInputs(`certification-cert_filter-tabs` = "Si")
app$setInputs(`certification-cert_filter-flt_samplesFe` = character(0), wait_=FALSE, values_=FALSE)
app$setInputs(`certification-cert_filter-precisionFe` = 4, wait_=FALSE, values_=FALSE)
app$setInputs(`certification-cert_filter-tabs` = "Fe")
app$setInputs(`certification-cert_filter-flt_samplesCu` = character(0), wait_=FALSE, values_=FALSE)
app$setInputs(`certification-cert_filter-precisionCu` = 4, wait_=FALSE, values_=FALSE)
app$setInputs(`certification-cert_filter-tabs` = "Cu")
app$setInputs(`certification-cert_filter-flt_samplesMn` = character(0), wait_=FALSE, values_=FALSE)
app$setInputs(`certification-cert_filter-precisionMn` = 4, wait_=FALSE, values_=FALSE)
app$setInputs(`certification-cert_filter-tabs` = "Mn")
app$setInputs(`certification-cert_filter-flt_samplesMg` = character(0), wait_=FALSE, values_=FALSE)
app$setInputs(`certification-cert_filter-precisionMg` = 4, wait_=FALSE, values_=FALSE)
app$setInputs(`certification-cert_filter-tabs` = "Mg")
app$setInputs(`certification-cert_filter-flt_samplesCr` = character(0), wait_=FALSE, values_=FALSE)
app$setInputs(`certification-cert_filter-precisionCr` = 4, wait_=FALSE, values_=FALSE)
app$setInputs(`certification-cert_filter-tabs` = "Cr")
app$setInputs(`certification-cert_filter-flt_samplesNi` = character(0), wait_=FALSE, values_=FALSE)
app$setInputs(`certification-cert_filter-precisionNi` = 4, wait_=FALSE, values_=FALSE)
app$setInputs(`certification-cert_filter-tabs` = "Ni")
app$setInputs(`certification-cert_filter-flt_samplesZn` = character(0), wait_=FALSE, values_=FALSE)
app$setInputs(`certification-cert_filter-precisionZn` = 4, wait_=FALSE, values_=FALSE)
app$setInputs(`certification-cert_filter-tabs` = "Zn")
app$setInputs(`certification-cert_filter-flt_samplesZn` = "8")
app$setInputs(`certification-cert_filter-flt_samplesZn` = c("8", "24"))
app$setInputs(`certification-cert_filter-flt_samplesZn` = c("8", "24", "32"))
app$snapshot()
app$setInputs(`certification-cert_filter-precisionZn` = 5)
app$snapshot()
app$setInputs(`certification-cert_filter-tabs` = "Ni")
app$setInputs(`certification-cert_filter-flt_samplesNi` = "23")
app$setInputs(`certification-cert_filter-flt_samplesNi` = c("23", "15"))
app$snapshot()
app$setInputs(`certification-cert_filter-tabs` = "Zn")
app$snapshot()
