app <- ShinyDriver$new("../../")
app$snapshotInit("first test")

app$setInputs(navbarpage = "Start")
app$setInputs(`excelfile-moduleSelect` = "Certifications")
app$uploadFile(`excelfile-test-upld-xlsxfile-file` = c("../../../extdata/Ergebnisblatt_BAM-M321_Aleris Koblenz_m.xlsx", "../../../extdata/Ergebnisblatt_BAM-M321_Aleris_Duffel_m.xlsx", "../../../extdata/Ergebnisblatt_BAM-M321_AMAG_Nasschemie_m.xlsx")) # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$setInputs(`excelfile-test-pam-colslider` = c(1, 13))
app$setInputs(`excelfile-test-pam-colslider` = c(1, 8))
app$setInputs(`excelfile-test-pam-rowslider` = c(7, 28))
app$setInputs(`excelfile-test-pam-rowslider` = c(7, 19))
app$setInputs(`excelfile-test-pam-rowslider` = c(7, 16))
app$setInputs(`excelfile-test-pam-rowslider` = c(7, 15))
app$setInputs(`excelfile-test-pam-rowslider` = c(7, 14))
app$setInputs(`excelfile-go` = "click")
app$snapshot()
app$setInputs(`certification-cert_filter-sel_analyt` = "Mn")
app$snapshot()
app$setInputs(`certification-cert_filter-flt_samples` = "20")
app$setInputs(`certification-cert_filter-flt_samples` = c("20", "12"))
app$snapshot()
