app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(link_to_start = "click")
app$setInputs(moduleSelect = "Certifications")
app$uploadFile(`excelfile-excel_file` = c("Ergebnisblatt_BAM-M321_Aleris Koblenz_m.xlsx", "Ergebnisblatt_BAM-M321_Aleris_Duffel_m.xlsx", "Ergebnisblatt_BAM-M321_AMAG_Nasschemie_m.xlsx")) # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$setInputs(`excelfile-go` = "click")
app$setInputs(`certification-analyteModule-flt_samplesSi` = character(0))
app$setInputs(`certification-analyteModule-precisionSi` = 4)
app$setInputs(`certification-analyteModule-flt_samplesFe` = character(0))
app$setInputs(`certification-analyteModule-precisionFe` = 4)
app$setInputs(`certification-analyteModule-flt_samplesCu` = character(0))
app$setInputs(`certification-analyteModule-precisionCu` = 4)
app$setInputs(`certification-analyteModule-flt_samplesMn` = character(0))
app$setInputs(`certification-analyteModule-precisionMn` = 4)
app$setInputs(`certification-analyteModule-flt_samplesMg` = character(0))
app$setInputs(`certification-analyteModule-precisionMg` = 4)
app$setInputs(`certification-analyteModule-flt_samplesCr` = character(0))
app$setInputs(`certification-analyteModule-precisionCr` = 4)
app$setInputs(`certification-analyteModule-flt_samplesNi` = character(0))
app$setInputs(`certification-analyteModule-precisionNi` = 4)
app$setInputs(`certification-analyteModule-flt_samplesZn` = character(0))
app$setInputs(`certification-analyteModule-precisionZn` = 4)
app$snapshot()
