---
params:
  Homogeneity: NA
---

## eCerto Report Homogeneity

**Date: `r format(Sys.time(), '%d %B, %Y')`**

*Test-Output // Designphase*

### Modul: Homogeneity

```{r data, echo=FALSE}
# get a local representation of all data provided by Shiny
H <- params$Homogeneity
h_dat <- H[["data"]]
```

`r ifelse(length(unique(h_dat[,"analyte"])>=2), "These are the Homogeneity boxplots:", "This is the Homogeneity boxplot:")`

```{r, echo=FALSE, comment=NA}
h_precision <- 4
if (!("H_type" %in% colnames(h_dat))) h_dat[,"H_type"] <- factor(rep("hom",nrow(h_dat)))
for (a in levels(interaction(h_dat[,"analyte"],h_dat[,"H_type"]))) {
  tmp <- h_dat[interaction(h_dat[,"analyte"],h_dat[,"H_type"])==a,]
  tmp[,"Flasche"] <- factor(tmp[,"Flasche"])
  omn <- round(mean(tmp[,"value"],na.rm=T), h_precision)
  osd <- round(stats::sd(tmp[,"value"],na.rm=T), h_precision)
  graphics::par(mar=c(5,4,6,0)+0.1)
  graphics::plot(x=c(0.6,0.4+length(levels(tmp[,"Flasche"]))), y=range(tmp[,"value"],na.rm=T), 
                 type="n", xlab="Flasche", ylab=paste0(a, " [", unique(tmp["unit"]),"]"), axes=F)
  graphics::abline(h=omn, lty=2)
  graphics::abline(h=omn+c(-1,1)*osd, lty=2, col=grDevices::grey(0.8))
  graphics::boxplot(tmp[,"value"] ~ tmp[,"Flasche"], add=TRUE)
  graphics::mtext(text = paste("Overall mean =", omn), side = 3, line = 2.45, adj = 1)
  graphics::mtext(text = paste("Overall sd =", osd), side = 3, line = 1.3, adj = 1)
}
```

This is the table of uncertainties associated with homogeneity:

```{r, echo=FALSE, comment=NA}
knitr::kable(H[["h_vals"]], row.names=FALSE, format="latex", format.args = list(decimal.mark = "."))
```

This is the table of input data:

```{r, echo=FALSE, comment=NA}
knitr::kable(H[["data"]], row.names=FALSE, format="latex", format.args = list(decimal.mark = "."))
```

End of Report.