tabsetPanel(
  id = 'tsP_help',
  tabPanel(
    title="Overview", 
    helpText("This Shiny/R based Online-Tool is intended to facilitate the statistics necessary to evaluate measurement data gained throughout coordinated trials (Ringversuch).")
  ),
  tabPanel(
    title="Certification", 
    h4("User/Study information and data backup/retrieval"), 
      helpText("For the eCerto module of the software you should provide a user name and trial id which will be stored together with your data ('Save Current Analysis').",
               "Previous analyses can be read from a backup file and contain all input data, parameters set during analysis and results."),
      imageOutput("myImage09", inline=TRUE),
    hr(),
    h4("Data upload from Excel for a new analysis"), 
      helpText("To process a new analysis, please collect all data which should be retuned in pre-defined Excel-Files by your certification trial partners and stored within one folder.",
               "Pre-defined means that the analytical results are at the same position within each file (table name, row and column range) and that one file per laboratory exists",
               strong("Note!"), "Header row should be specified but will not be evaluated. eCerto assumes the first and second column to contain analyte names and units respectively and replicate measurements of this analyte in all remaining columns.",
               strong("Note!"), "Filenames will be stored for reference but imported labs will be consecutively numbered.",
               "In the example below you would import data from table 'Tabelle1' located in Range A1:D5, containing 2 replicate measurements of 4 different analytes measured in ", HTML("&#8451;"), ".",
               "Instead of the table name you could as well provide a number specifying the sheet number in your excel files (in this case you could input '1' as only one sheet is contained in the file)."),
      #imageOutput("myImage01", inline=TRUE),
      imageOutput("myImage02", inline=TRUE),
      helpText("Upload starts once files have been selected via 'Browse'-button.",
               strong("Note!"), "Currently, eCerto needs to load all Excel-result files in one step, i.e. you can not add additional files later on but would have to start all over again."),
    hr(),
    h4("Laboratory statistics to identify potentially outliers for lab means and/or lab variances"), 
      helpText("For the selected analyte various statistical tests regarding lab means and variance will be performed according to ISO 17025 and outlying values will be indicated if observed at the .05 and .01 level respectively"),
      imageOutput("myImage03", inline=TRUE), 
      helpText("eCerto uses functions available for the statistical software environment R.", 
               "Details regarding the conducted statistical test (implementation, parameters) can be found using the following links:"),
      tags$li(a("Scheffe", href="https://rdrr.io/cran/agricolae/man/scheffe.test.html", target="_blank")), 
      tags$li(a("Dixon", href="https://rdrr.io/cran/outliers/man/dixon.test.html", target="_blank")),
      tags$li(a("Grubbs", href="https://rdrr.io/cran/outliers/man/grubbs.test.html", target="_blank")),
      tags$li(a("Nalimov", href="http://www.statistics4u.info/fundstat_germ/ee_nalimov_outliertest.html", target="_blank")),
      tags$li(a("Cochran", href="https://rdrr.io/cran/outliers/man/cochran.test.html", target="_blank")),
      hr(),
    h4("Statistics on the lab means distribution"), 
      helpText("The distribution of lab means is evaluated using a variety of recommended tests. Normality is tested using the KS-Test.",
               strong("Note!"), "Some tests need a minimum number of replicates and will not yield a result if this criteria is not met (i.e. Agostino)."),
      imageOutput("myImage04", inline=TRUE),
      helpText("Details regarding the conducted statistical test can be found using the following links:"),
      tags$li(a("Bartlett", href="https://rdrr.io/cran/stats/man/bartlett.test.html", target="_blank")),
      tags$li(a("ANOVA", href="https://rdrr.io/cran/stats/man/anova.html", target="_blank")),
      tags$li(a("KS", href="https://rdrr.io/cran/stats/man/ks.test.html", target="_blank")),
      tags$li(a("Skewness", href="https://rdrr.io/cran/moments/man/skewness.html", target="_blank")),
      tags$li(a("Agostino", href="https://rdrr.io/cran/moments/man/agostino.test.html", target="_blank")),
      tags$li(a("Kurtosis", href="https://rdrr.io/cran/moments/man/kurtosis.html", target="_blank")),
      tags$li(a("Anscombe", href="https://rdrr.io/cran/moments/man/anscombe.test.html", target="_blank")),
    hr(),
    h4("Certified value calculation and vizualization of the currently selected analyte"), 
      helpText("Lab means and distribution is depicted in a standard graphic layout which can be exported as vector graphic (PDF) for further editing.",
               "Labs which have been identified as outliers above can be excluded from the overall mean calculation.", 
               "This decision has to be made by the user, eCerto will not remove an outlier lab automatically."),
      imageOutput("myImage05", inline=TRUE),
    hr(),
    h4("Export Reports of the currently selected analyte or the certified values of all analytes"), 
      helpText("A report of the above analysis (single analyte) or for the material (all analytes) can be generated and exported in different formats."),
      imageOutput("myImage07", inline=TRUE),
      helpText("Certified values for each analyte (following individual inspection) are transfered to a table for the material.", 
               "Several columns of this table can be edited by the user by clicking in an individual cell and changing the value.", 
               strong("Note!"), "While certified values could be calculated directly after data upload this is only done on a per analyte basis to enforce manual inspection of the data by the user."),
      imageOutput("myImage06", inline=TRUE),
      helpText("However, this is not yet the final state and just a technical demonstration [ToDo].")
  ),
  tabPanel(
    title="Homogeneity", 
    h4("Data upload"), 
      helpText("Please prepare all data in a single Excel file on the first table (other tables will be neglected). Please stick to the header/format as given in the below example. The 'analyte' column should contain values that match the corresponding data from the certification module. 'H_type' can be used to define different homogeneity traits for each analyte which can yield independent uncertainty contributions. 'Flasche' encodes the different samples where repeated measurements have been performed on. 'value'/'unit' habe to be determined similarly to the data from the certification trial obviously to yield a meaningful uncertainty value."),
      imageOutput("myImage08", inline=TRUE),
      helpText("Upload can be also achieved from a previousy created backup file. If a backup file does not contain any homogeneity data, an Excel upload option will remain active but will be deactivated otherwise."),
    hr(),
    h4("Statistics"), 
      helpText("The uncertainty contribution of the Homogeneity measurements U_bb is calculated for each analyte based on formula $$ and is transfered to the materials table of the certification module in case that an analyte of matching name is found."),
    hr(),
    h4("Report"), 
      helpText("Figures and tables can currently be exported in a HTML format."),
    hr()
  ),
  tabPanel(
   title="Stability", 
   h4("Data upload"), 
   helpText("Please prepare data in a single Excel file on seperate tables for each analyte as shown in the below example. Table names have to match analyte names from the Certification module. Column names need to be exactly 'Value' and 'Date' and column format should be numeric and date respectively."),
   imageOutput("myImage10", inline=TRUE),
   helpText("Upload can be also achieved from a previousy created backup file. If a backup file does not contain any stability data, the Excel upload option will remain active but will be deactivated otherwise."),
   hr(),
   h4("Output"), 
   helpText("The uncertainty contribution of the stability measurements U_Stab is calculated for each analyte based on formula $$ and is transfered to the materials table of the certification module in case that an analyte of matching name is found.")
  ),
  tabPanel(
    title="LTS", 
    h4("Data upload"), 
    helpText("Please prepare data in a single Excel file on seperate tables for each measured value (KW, Kennwert) as shown in the below example. Table/File names are not evaluated. Instead, each table is expected to contain the metadata in rows 1-2 and the measurement data from row 4 onwards. Column names need to be exactly as in the example and should match the desired format (e.g. 'Value' and 'Date' columns should be of numeric and date format respectively)."),
    imageOutput("myImage11", inline=TRUE),
    hr(),
    h4("Output"), 
    helpText("The Tool calculates the expected life time of a reference material in two steps (i) by calculating a linear model for the measurement data (y = m*x + n, time expressed in month) and (ii) by correcting the measurement data w.r.t. the certified value using the obtained 'n' before using the obtained 'm' to estimate the timepoint when y is exceeding the range of CetVal+-U.")
  )
)