---
title: "*eCerto* (Statistics for CRM production)"
output:
  #html_document:
    #toc: true
    #toc_depth: 3
    #toc_float:
    #  collapsed: false
    #  smooth_scroll: false
    #embed-resources: true
    #standalone: true
  html:
    options:
      toc:
        depth: 3
        number_sections: true
      embed-resources: true
    meta:
      css: ["@default", "@heading-anchor"]
      js: ["@sidenotes", "@heading-anchor"]
---


```{css, eval = FALSE, echo = FALSE}

.tocify-header {
  text-indent: initial;
}

.tocify-subheader > .tocify-item {
  text-indent: initial;
  padding-left: 25px;
}

.tocify-subheader .tocify-subheader > .tocify-item {
  text-indent: initial;
  padding-left: 50px;
}

.tocify-subheader .tocify-subheader .tocify-subheader > .tocify-item {
  text-indent: initial;
  padding-left: 60px;
}

div.figcaption {
  font-size: 0.8em;
  background: rgba(0, 0, 0, 0.04);
  padding: 2px;
  margin-top: 4px;
  margin-bottom: 10px;
}
```

```{r child = 'start.Rmd'}
```

```{r child = 'certification.Rmd'}
```

```{r child = 'homogeneity.Rmd'}
```

```{r child = 'stability.Rmd'}
```

```{r child = 'certified_values.Rmd'}
```

---

```{r child = 'lts.Rmd'}
```

```{r child = 'validation.Rmd'}
```
