### Stability data upload

Stability data can be uploaded from an Excel file containing a single table
including columns `analyte`, `Date`, `Value` and (optionally) `unit`. 
An additional column `Temp` can be included. If present, *eCerto* will try to 
perform shelf life calculations based on the Arrhenius model.

*eCerto* will internally use the format "yyyy-mm-dd" for date values. It will try
hard to convert other formats like "dd.mm.yyyy" from Excel correctly. Specifying 
a date instead of a relative time information is required to calculate shelf time 
and allows to continue using this data for long term stability monitoring.

```{r S_upload_format, echo=FALSE, message=FALSE}
x <- cbind(eCerto:::test_Stability_Arrhenius()[1:12,c(1,2,4,5)], "unit" = "mg/kg")
ft <- eCerto:::show_upload_example_table(x=x, optional=c(4,5))
flextable::set_caption(ft, caption = flextable::as_paragraph(
  flextable::as_b("Info"), " Example table layout for stability data upload, including (optional) temperature information to perform Arrhenius calculations"))
```

The `Temp` column obviously should contain temperature levels in °C at which 
samples were stored before measurement. The lowest temperature level will be 
used as a reference point $T_\mathit{ctrl}$. This is also reflected in the 
specified `Date` values, where $T_\mathit{ctrl}$ will be treated as a reference 
time point. All other temperature levels should have *later* dates specified. 
For every measurement, the difference between its date and the reference time 
point will be computed to represent the storage time at this temperature.

Using dates instead of specifying storage time directly allows to compute 
stability and potential shelf life in both, relative (month) and absolute (date)
values.

Upload can be also achieved from a previously created backup file.
