### Stability uncertainty calculation

The parameters of all linear models are collected in **Tab.S1** and the potential
uncertainty contribution of the material stability is obtained from formula 
$u_{stab}={|t_{cert} \times s(b_1)| \over \mu_s}$ where $t_{cert}$ is the expected shelf life 
of the CRM (in month) and $s(b_1)$ is the standard error `SE` of the slope of 
the linear model. $\mu_s$ is calculated as the mean of all values of an analyte
depicted in **Fig.S1**, i.e. all values included in the linear model calculation.

The expected shelf life can be set by the user and should incorporate the time 
until the first certification monitoring and the certified shelf life of the 
material. This estimation of stability uncertainty is based on section 8.7.3 of 
ISO GUIDE 35:2017 and valid in the absence of a significant trend.

To determine if the slope $b_1$ is significantly different from $b_1=0$ we 
perform a t-test by calculating the t-statistic $t_m = |b_1| / s(b_1)$ and 
compare the result with the two-tailed critical value of Student's $t$ 
for $n - 2$ degrees of freedom to obtain the P-values in column P~b1~.

```{r TabS1, echo=FALSE, message=FALSE, resize.width="100%", results='asis'}
x <- eCerto:::prepTabS1(x = eCerto:::test_Stability_Excel())
eCerto:::styleTabS1(x = x, mt = NULL, sr = 1, output = "ft")
```

***Note!***
Selecting a table row in Tab.S1 will display the detailed analysis for the
respective analyte.

Values from column `u_stab_` can be transferred to a user defined column of the 
material table **Tab.C3** in the certification module for matching analyte names. 
Analytes of **Tab.S1** which can not be matched to **Tab.C3** are depicted in red.

Also $P_{b1}$ values lower than 0.05 are highlighted in red to indicate a slope
significantly different from 0.