#'Report_Vorlage.Rmd
#'genarated using: dput(readLines("C:/Users/jlisec/Documents/Projects/BAMTool_Backup/Report_Vorlage_Analyt.Rmd"))
Report_Vorlage_Analyt <- function() {
  c("---", "params:", " res: NA", "---", "", "## BAM Tool Report", 
    "", "**Study ID: `r params$General$study_id`**", "", 
    "**Analyte: `r params$res$Certification$opt$sel_analyt`**", "", 
    "**User: `r params$General$user`**", "", "**Date: `r format(Sys.time(), '%d %B, %Y')`**", 
    "", "*Testoutput // Designphase*", "", "### Modul: Certification", 
    "", "```{r data, echo=FALSE}", "# get a local representation of all data provided by Shiny", 
    "Zertifizierung <- params$res$Certification", "data <- Zertifizierung$data", 
    "precision <- Zertifizierung$precision", "```", "", "These files have been provided to the tool by `r params$General$user`:", 
    "", "```{r data_files, echo=FALSE, comment=NA}", "cat(paste(Zertifizierung$input_files, collapse=\", \"))", 
    "```", "", "`r ifelse(any(!Zertifizierung$opt$flt_samples==\"\"), \"The following samples (IDs) have been removed by the user:\", \"\")`", 
    "", "```{r, eval=any(!Zertifizierung$opt$flt_samples==\"\"), echo=FALSE, comment=NA}", 
    "cat(paste(Zertifizierung$opt$flt_samples, collapse=\", \"))", 
    "```", "", "This is the imported data which was basis for all further calculations:", 
    "", "```{r data_table, echo=FALSE}", "if (Zertifizierung$opt$data_style==\"kompakt\") {", 
    "  knitr::kable(params$res$Certification$data_kompakt, row.names=FALSE, format.args = list(decimal.mark = \",\"))", 
    "} else {", "  knitr::kable(data, row.names=FALSE, format.args = list(decimal.mark = \",\"))", 
    "}", "```", "", "`r ifelse(Zertifizierung$stats$show, \"\", \"### Statistics regarding lab means, lab variances and outlier detection\")`", 
    "", "```{r eval=!Zertifizierung$stats$show, echo=FALSE, comment=NA}", 
    "Stats <- eval(parse(text=Zertifizierung$stats$fnc))", "if (Zertifizierung$opt$show_code) {", 
    "  cat(\"Function call:\\n\")", "  tmp <- deparse(Stats, width.cutoff = 56L)", 
    "  for (i in 1:length(tmp))  {cat(tmp[i]);cat(\"\\n\")}", "}", 
    "cat(paste(\"Selected precision:\", precision, \"\\n\"))", "knitr::kable(eval(Zertifizierung$stats$call), row.names=FALSE, format.args = list(decimal.mark = \",\"))", 
    "```", "", "`r ifelse(Zertifizierung$mstats$show, \"\", \"### Statistics regarding overall mean distribution and variance testing\")`", 
    "", "```{r eval=!Zertifizierung$mstats$show, echo=FALSE, comment=NA}", 
    "mstats <- eval(parse(text=Zertifizierung$mstats$fnc))", "if (Zertifizierung$opt$show_code) {", 
    "  cat(\"Function call:\\n\")", "  tmp <- deparse(mstats, width.cutoff = 56L)", 
    "  for (i in 1:length(tmp))  {cat(tmp[i]);cat(\"\\n\")}", "}", 
    "cat(paste(Zertifizierung$normality_statement, \"\\n\"))", "knitr::kable(eval(Zertifizierung$mstats$call), row.names=FALSE, format.args = list(decimal.mark = \",\"))", 
    "```", "", "`r ifelse(Zertifizierung$CertValPlot$show, \"\", \"### Certified Values Plot\")`", 
    "", "```{r, eval=!Zertifizierung$CertValPlot$show, echo=FALSE, comment=NA, fig.width=Zertifizierung$CertValPlot$Fig01_width/72, fig.height=Zertifizierung$CertValPlot$Fig01_height/72}", 
    "CertValPlot <- eval(parse(text=Zertifizierung$CertValPlot$fnc))", 
    "if (Zertifizierung$opt$show_code) {", "  cat(\"Function call:\\n\")", 
    "  tmp <- deparse(CertValPlot)", "  for (i in 1:length(tmp)) {cat(tmp[i]);cat(\"\\n\")}", 
    "}", "eval(Zertifizierung$CertValPlot$call)", "```", "", "End of Report."
  )
}